query TopRepositories($first: Int!, $after: String) { # busca em lotes, ver Issue #13
  search(
    query: "stars:>0 sort:stars-desc"
    type: REPOSITORY
    first: $first
    after: $after
  ) {
    repositoryCount
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      ... on Repository {
        nameWithOwner
        stargazerCount
        createdAt # para calc o req 1
        pullRequests(states: MERGED) { # para calc req 2
          totalCount
        }
        releases { # RQ03
          totalCount
        }
        updatedAt # RQ04
        primaryLanguage { # RQ05
          name
        }
        issues { # RQ06 (total)
          totalCount
        }
        closedIssues: issues(states: CLOSED) { # RQ06 (fechadas)
          totalCount
        }
      }
    }
  }
}
