query TopRepositories($first: Int!) { # quantidade de repositorios passado por parametro, consulta única
  search(
    query: "stars:>0 sort:stars-desc"
    type: REPOSITORY
    first: $first
  ) {
    repositoryCount
    nodes {
      ... on Repository {
        nameWithOwner
        stargazerCount
        createdAt # para calc o req 1
        pullRequests(states: MERGED) { # para calc req 2
          totalCount
        }
        releases { # RQ03
          totalCount
        }
        updatedAt # RQ04
      }
    }
  }
}
